# GX Load Package and Context

In [7]:
import pandas as pd
import great_expectations as gx
context = gx.data_context.DataContext('./gx')

In [8]:
df = pd.read_parquet('./green_tripdata_2023-07.parquet')
df['lpep_pickup_datetime'] = df['lpep_pickup_datetime'].astype('str')
df['lpep_dropoff_datetime'] = df['lpep_dropoff_datetime'].astype('str')

# Create New Great Expectation Project

In [ ]:
from  gx.plugins.expectations.expect_column_values_to_be_non_negative import ExpectColumnValuesToBeNonNegative

In [7]:
dataframe_asset = context.sources.add_pandas(
    "green_taxi_validator_checkpoint"
).add_dataframe_asset(
    name="taxi_df", dataframe=df, batch_metadata={"year": "2023", "month": "07"}
)
batch_request = dataframe_asset.build_batch_request()

context.add_or_update_expectation_suite("green_taxi_expectation_suite")
validator = context.get_validator(
    batch_request=batch_request,
    expectation_suite_name="green_taxi_expectation_suite",
)
validator.head()

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2.0,2023-07-01 00:08:06,2023-07-01 00:21:24,N,1.0,75.0,170.0,2.0,3.45,17.0,1.0,0.5,4.45,0.0,NaN,1.0,26.70,1.0,1.0,2.75
1,2.0,2023-07-01 00:56:14,2023-07-01 01:03:28,N,1.0,75.0,262.0,2.0,1.49,10.0,1.0,0.5,3.05,0.0,NaN,1.0,18.30,1.0,1.0,2.75
2,2.0,2023-06-30 23:47:32,2023-06-30 23:47:35,N,5.0,42.0,42.0,2.0,0.00,50.0,0.0,0.0,15.30,0.0,NaN,1.0,66.30,1.0,2.0,0.00
3,2.0,2023-07-01 00:30:12,2023-07-01 00:51:20,N,1.0,33.0,75.0,1.0,9.32,38.0,1.0,0.5,0.00,0.0,NaN,1.0,43.25,2.0,1.0,2.75
4,2.0,2023-07-01 00:46:56,2023-07-01 00:49:02,N,1.0,74.0,74.0,1.0,0.97,5.8,1.0,0.5,0.00,0.0,NaN,1.0,8.30,1.0,1.0,0.00

In [9]:
# validator.expect_column_values_to_not_be_null(column="VendorID")
# validator.expect_column_values_to_match_strftime_format(column="lpep_pickup_datetime", strftime_format="%Y-%m-%d %H:%M:%S")
validator.expect_column_values_to_match_strftime_format(column="lpep_pickup_datetime", strftime_format="%Y-%m-%d %H:%M:%S")
validator.expect_column_values_to_match_strftime_format(column="lpep_dropoff_datetime", strftime_format="%Y-%m-%d %H:%M:%S")
validator.expect_column_values_to_be_non_negative(column="passenger_count")
validator.expect_column_values_to_be_non_negative(column="trip_distance")
validator.expect_column_values_to_be_non_negative(column="tolls_amount")
validator.save_expectation_suite(discard_failed_expectations=False)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

In [10]:
checkpoint = context.add_or_update_checkpoint(
    name="green_taxi_checkpoint",
    validations=[
        {
            "batch_request": batch_request,
            "expectation_suite_name": "green_taxi_expectation_suite",
        },
    ],
)
results = checkpoint.run()
results

Calculating Metrics:   0%|          | 0/38 [00:00<?, ?it/s]

{
  "run_id": {
    "run_name": null,
    "run_time": "2023-10-31T15:27:11.456007+01:00"
  },
  "run_results": {
    "ValidationResultIdentifier::green_taxi_expectation_suite/__none__/20231031T142711.456007Z/green_taxi_validator_checkpoint-taxi_df": {
      "validation_result": {
        "success": true,
        "results": [
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_column_values_to_match_strftime_format",
              "kwargs": {
                "column": "lpep_pickup_datetime",
                "strftime_format": "%Y-%m-%d %H:%M:%S",
                "batch_id": "green_taxi_validator_checkpoint-taxi_df"
              },
              "meta": {}
            },
            "result": {
              "element_count": 61343,
              "unexpected_count": 0,
              "unexpected_percent": 0.0,
              "partial_unexpected_list": [],
              "missing_count": 0,
              "missing_percent": 0.0,
              "unexpected_percent_total": 0.0,
              "unexpected_percent_nonmissing": 0.0,
              "partial_unexpected_counts": [],
              "partial_unexpected_index_list": []
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          },
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_column_values_to_match_strftime_format",
              "kwargs": {
                "column": "lpep_dropoff_datetime",
                "strftime_format": "%Y-%m-%d %H:%M:%S",
                "batch_id": "green_taxi_validator_checkpoint-taxi_df"
              },
              "meta": {}
            },
            "result": {
              "element_count": 61343,
              "unexpected_count": 0,
              "unexpected_percent": 0.0,
              "partial_unexpected_list": [],
              "missing_count": 0,
              "missing_percent": 0.0,
              "unexpected_percent_total": 0.0,
              "unexpected_percent_nonmissing": 0.0,
              "partial_unexpected_counts": [],
              "partial_unexpected_index_list": []
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          },
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_column_values_to_be_non_negative",
              "kwargs": {
                "column": "passenger_count",
                "batch_id": "green_taxi_validator_checkpoint-taxi_df"
              },
              "meta": {}
            },
            "result": {
              "element_count": 61343,
              "unexpected_count": 0,
              "unexpected_percent": 0.0,
              "partial_unexpected_list": [],
              "missing_count": 4732,
              "missing_percent": 7.7140015975742955,
              "unexpected_percent_total": 0.0,
              "unexpected_percent_nonmissing": 0.0,
              "partial_unexpected_counts": [],
              "partial_unexpected_index_list": []
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          },
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_column_values_to_be_non_negative",
              "kwargs": {
                "column": "trip_distance",
                "batch_id": "green_taxi_validator_checkpoint-taxi_df"
              },
              "meta": {}
            },
            "result": {
              "element_count": 61343,
              "unexpected_count": 0,
              "unexpected_percent": 0.0,
              "partial_unexpected_list": [],
              "missing_count": 0,
              "missing_percent": 0.0,
              "unexpected_percent_total": 0.0,
              "unexpected_percent_nonmissing": 0.0,
              "partial_unexpected_counts": [],
              "partial_unexpected_index_list": []
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          },
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_column_values_to_be_non_negative",
              "kwargs": {
                "column": "tolls_amount",
                "batch_id": "green_taxi_validator_checkpoint-taxi_df"
              },
              "meta": {}
            },
            "result": {
              "element_count": 61343,
              "unexpected_count": 0,
              "unexpected_percent": 0.0,
              "partial_unexpected_list": [],
              "missing_count": 0,
              "missing_percent": 0.0,
              "unexpected_percent_total": 0.0,
              "unexpected_percent_nonmissing": 0.0,
              "partial_unexpected_counts": [],
              "partial_unexpected_index_list": []
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          }
        ],
        "evaluation_parameters": {},
        "statistics": {
          "evaluated_expectations": 5,
          "successful_expectations": 5,
          "unsuccessful_expectations": 0,
          "success_percent": 100.0
        },
        "meta": {
          "great_expectations_version": "0.17.23",
          "expectation_suite_name": "green_taxi_expectation_suite",
          "run_id": {
            "run_name": null,
            "run_time": "2023-10-31T15:27:11.456007+01:00"
          },
          "batch_spec": {
            "batch_data": "PandasDataFrame"
          },
          "batch_markers": {
            "ge_load_time": "20231031T142711.487866Z",
            "pandas_data_fingerprint": "e6aa40ea5d5f819c87edfec5304c6fe4"
          },
          "active_batch_definition": {
            "datasource_name": "green_taxi_validator_checkpoint",
            "data_connector_name": "fluent",
            "data_asset_name": "taxi_df",
            "batch_identifiers": {}
          },
          "validation_time": "20231031T142711.556439Z",
          "checkpoint_name": "green_taxi_checkpoint",
          "validation_id": null,
          "checkpoint_id": null
        }
      },
      "actions_results": {
        "store_validation_result": {
          "class": "StoreValidationResultAction"
        },
        "store_evaluation_params": {
          "class": "StoreEvaluationParametersAction"
        },
        "update_data_docs": {
          "local_site": "file://e:\\New folder (2)\\gx\\uncommitted/data_docs/local_site/validations%5Cgreen_taxi_expectation_suite%5C__none__%5C20231031T142711.456007Z%5Cgreen_taxi_validator_checkpoint-taxi_df.html",
          "class": "UpdateDataDocsAction"
        }
      }
    }
  },
  "checkpoint_config": {
    "default_validation_id": null,
    "profilers": [],
    "notify_on": null,
    "expectation_suite_name": null,
    "batch_request": {},
    "notify_with": null,
    "run_name_template": null,
    "name": "green_taxi_checkpoint",
    "action_list": [
      {
        "name": "store_validation_result",
        "action": {
          "class_name": "StoreValidationResultAction"
        }
      },
      {
        "name": "store_evaluation_params",
        "action": {
          "class_name": "StoreEvaluationParametersAction"
        }
      },
      {
        "name": "update_data_docs",
        "action": {
          "class_name": "UpdateDataDocsAction"
        }
      }
    ],
    "ge_cloud_id": null,
    "runtime_configuration": {},
    "config_version": 1.0,
    "expectation_suite_ge_cloud_id": null,
    "class_name": "Checkpoint",
    "template_name": null,
    "slack_webhook": null,
    "evaluation_parameters": {},
    "validations": [
      {
        "name": null,
        "expectation_suite_name": "green_taxi_expectation_suite",
        "batch_request": {
          "datasource_name": "green_taxi_validator_checkpoint",
          "data_asset_name": "taxi_df",
          "options": {},
          "batch_slice": null
        },
        "id": null,
        "expectation_suite_ge_cloud_id": null
      }
    ],
    "module_name": "great_expectations.checkpoint",
    "site_names": null
  },
  "success": true
}

# Validate a pandas dataframe with existing Great Expectation expectations

In [9]:
df = pd.read_parquet('./green_tripdata_2023-07.parquet')
df['lpep_pickup_datetime'] = df['lpep_pickup_datetime'].astype('str')
df['lpep_dropoff_datetime'] = df['lpep_dropoff_datetime'].astype('str')

taxi_asset = context.get_datasource("green_taxi_validator_checkpoint").get_asset("taxi_df")
batch_request = taxi_asset.build_batch_request(dataframe=df)
checkpoint = context.get_checkpoint(name="green_taxi_checkpoint")
results = checkpoint.run_with_runtime_args(
    batch_request=batch_request,
    expectation_suite_name="green_taxi_expectation_suite"
)
results.success

Calculating Metrics:   0%|          | 0/38 [00:00<?, ?it/s]

True

# Validate Pandas Schema with Pandera

In [1]:
from urllib.error import HTTPError
import pandas as pd

df = None
try:
    df = pd.read_parquet("https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2023-07.parquet")
except HTTPError:
    print('the requested file is not available')

df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2.0,2023-07-01 00:08:06,2023-07-01 00:21:24,N,1.0,75.0,170.0,2.0,3.45,17.0,1.0,0.5,4.45,0.0,NaN,1.0,26.70,1.0,1.0,2.75
1,2.0,2023-07-01 00:56:14,2023-07-01 01:03:28,N,1.0,75.0,262.0,2.0,1.49,10.0,1.0,0.5,3.05,0.0,NaN,1.0,18.30,1.0,1.0,2.75
2,2.0,2023-06-30 23:47:32,2023-06-30 23:47:35,N,5.0,42.0,42.0,2.0,0.00,50.0,0.0,0.0,15.30,0.0,NaN,1.0,66.30,1.0,2.0,0.00
3,2.0,2023-07-01 00:30:12,2023-07-01 00:51:20,N,1.0,33.0,75.0,1.0,9.32,38.0,1.0,0.5,0.00,0.0,NaN,1.0,43.25,2.0,1.0,2.75
4,2.0,2023-07-01 00:46:56,2023-07-01 00:49:02,N,1.0,74.0,74.0,1.0,0.97,5.8,1.0,0.5,0.00,0.0,NaN,1.0,8.30,1.0,1.0,0.00

In [4]:
df.dtypes

In [11]:
from numpy import datetime64
from pandera.errors import SchemaError
from pandera import Column, DataFrameSchema, Float64, Index

schema = DataFrameSchema(
    {
        "VendorID": Column(Float64),
        "lpep_pickup_datetime": Column(datetime64),
        "lpep_dropoff_datetime": Column(datetime64),
        "store_and_fwd_flag": Column(object, nullable=True),
        "RatecodeID": Column(Float64, nullable=True),
        "PULocationID": Column(Float64),
        "DOLocationID": Column(Float64),
        "passenger_count": Column(Float64, nullable=True),
        "trip_distance": Column(Float64),
        "fare_amount": Column(Float64),
        "extra": Column(Float64),
        "mta_tax": Column(Float64),
        "tip_amount": Column(Float64),
        "tolls_amount": Column(Float64),
        "ehail_fee": Column(Float64, nullable=True),
        "improvement_surcharge": Column(Float64),
        "total_amount": Column(Float64),
        "payment_type": Column(Float64, nullable=True),
        "trip_type": Column(Float64, nullable=True),
        "congestion_surcharge": Column(Float64, nullable=True)
    },
    index=Index(int),
    strict=True,
)

try:
    schema.validate(df)
except SchemaError:
    print('schema error')

# Another

In [27]:
import pandas as pd
import great_expectations as gx


context = gx.get_context(context_root_dir="./gx/initial_gx")

[]

In [28]:
expectations_store = context.expectations_store

# List all expectation suite keys in the store
suite_keys = expectations_store.list_keys()
print("Suite keys in store:", suite_keys)

Suite keys in store: [ExpectationSuiteIdentifier::green_taxi_expectation_suite]

In [ ]:
import pandas as pd 

df = pd.read_parquet('C:\\Users\\ad103731\\Downloads\\green_tripdata_2025-02.parquet', engine='pyarrow')
df.columns

In [13]:
import pandas as pd 

df = pd.read_parquet('C:\\Users\\ad103731\\Downloads\\green_tripdata_2026-01.parquet', engine='pyarrow')
df.columns

Index(['VendorID', 'lpep_pickup_datetime', 'lpep_dropoff_datetime',
       'store_and_fwd_flag', 'RatecodeID', 'PULocationID', 'DOLocationID',
       'passenger_count', 'trip_distance', 'fare_amount', 'extra', 'mta_tax',
       'tip_amount', 'tolls_amount', 'ehail_fee', 'improvement_surcharge',
       'total_amount', 'payment_type', 'trip_type', 'congestion_surcharge',
       'cbd_congestion_fee'],
      dtype='object')

In [14]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,1,2026-01-01 00:27:58,2026-01-01 00:55:16,N,1.0,65,233,2.0,6.20,31.7,...,1.5,7.5,0.0,NaN,1.0,45.20,1.0,1.0,2.75,0.75
1,2,2026-01-01 00:44:33,2026-01-01 01:32:56,N,5.0,66,188,5.0,5.36,50.0,...,0.0,10.2,0.0,NaN,1.0,61.20,1.0,2.0,0.00,0.00
2,1,2026-01-01 00:23:45,2026-01-01 00:45:03,N,1.0,65,179,4.0,10.60,41.5,...,1.5,2.0,0.0,NaN,1.0,46.00,1.0,1.0,0.00,0.00
3,1,2026-01-01 00:44:33,2026-01-01 01:00:45,N,1.0,42,141,1.0,4.20,19.8,...,1.5,0.0,0.0,NaN,1.0,25.05,2.0,1.0,2.75,0.00
4,2,2026-01-01 00:46:04,2026-01-01 01:04:40,N,1.0,95,82,1.0,2.76,19.1,...,0.5,0.0,0.0,NaN,1.0,21.60,2.0,1.0,0.00,0.00

In [4]:
df['store_and_fwd_flag'].unique()

array(['N', 'Y', None], dtype=object)

In [15]:
df.drop(columns=['store_and_fwd_flag'], inplace=True)

In [25]:
import fluss

BOOTSTRAP_SERVERS = "coordinator-server:9123"


config = fluss.Config({"bootstrap.servers": "127.0.0.1:9123"})
conn = await fluss.FlussConnection.create(config)
admin = conn.get_admin()

FlussError: FlussError: Fluss hitting unexpected rpc error connection error: ConnectionError("IO Error: No connection could be made because the target machine actively refused it. (os error 10061)")

In [22]:
await admin.get_server_nodes()

[ServerNode(id=0, host='coordinator-server', port=9123, server_type='CoordinatorServer'),
 ServerNode(id=0, host='tablet-server', port=9124, server_type='TabletServer')]

In [18]:
await admin.get_database_info("fluss")

FlussError: FlussError: Fluss hitting unexpected rpc error connection error: ConnectionError("IO Error: No such host is known. (os error 11001)")

In [10]:
await admin.create_database("lakehouse_db", ignore_if_exists=True)

FlussError: FlussError: Fluss hitting unexpected rpc error connection error: ConnectionError("IO Error: No such host is known. (os error 11001)")

In [6]:
table_path = fluss.TablePath("lakehouse_db", "green_taxi_2025_01")

In [7]:
from datetime import datetime, timezone

import fluss
import pandas as pd
import pyarrow as pa

BOOTSTRAP_SERVERS = "coordinator-server:9123"

SCHEMA = fluss.Schema(
    pa.schema(
        [
            pa.field("vendor_id", pa.int32()),
            pa.field("lpep_pickup_datetime", pa.timestamp("us")),
            pa.field("lpep_dropoff_datetime", pa.timestamp("us")),
            pa.field("rate_code_id", pa.int32()),
            pa.field("pu_location_id", pa.int32()),
            pa.field("do_location_id", pa.int32()),
            pa.field("passenger_count", pa.int32()),
            pa.field("trip_distance", pa.float64()),
            pa.field("fare_amount", pa.float64()),
            pa.field("extra", pa.float64()),
            pa.field("mta_tax", pa.float64()),
            pa.field("tip_amount", pa.float64()),
            pa.field("tolls_amount", pa.float64()),
            pa.field("ehail_fee", pa.float64()),
            pa.field("improvement_surcharge", pa.float64()),
            pa.field("total_amount", pa.float64()),
            pa.field("payment_type", pa.int32()),
            pa.field("trip_type", pa.int32()),
            pa.field("congestion_surcharge", pa.float64()),
            pa.field("cbd_congestion_fee", pa.float64()),
        ]
    )
)

In [8]:
descriptor = fluss.TableDescriptor(SCHEMA)

admin.create_table(table_path, descriptor, ignore_if_exists=True)

In [1]:
import pandas as pd 

pd.read_parquet("C:\\00000-0-a1a04937-6f0a-443c-be79-c125d2f069e1-00001.parquet")

,vendor_id,lpep_pickup_datetime,lpep_dropoff_datetime,rate_code_id,pu_location_id,do_location_id,passenger_count,trip_distance,fare_amount,extra,...,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee,__bucket,__offset,__timestamp
0,2,2025-01-01 00:03:01,2025-01-01 00:17:12,1.0,75,235,1.0,5.93,24.70,1.0,...,NaN,1.0,34.00,1.0,1.0,0.00,0.0,0,0,2026-09-18 18:22:34.178000+00:00
1,2,2025-01-01 00:19:59,2025-01-01 00:25:52,1.0,166,75,1.0,1.32,8.60,1.0,...,NaN,1.0,11.10,2.0,1.0,0.00,0.0,0,1,2026-09-18 18:22:34.178000+00:00
2,2,2025-01-01 00:05:29,2025-01-01 00:07:21,5.0,171,73,1.0,0.41,25.55,0.0,...,NaN,1.0,26.55,2.0,2.0,0.00,0.0,0,2,2026-09-18 18:22:34.178000+00:00
3,2,2025-01-01 00:52:24,2025-01-01 01:07:52,1.0,74,223,1.0,4.12,21.20,1.0,...,NaN,1.0,36.77,1.0,1.0,0.00,0.0,0,3,2026-09-18 18:22:34.178000+00:00
4,2,2025-01-01 00:25:05,2025-01-01 01:01:10,1.0,66,158,1.0,4.71,33.80,1.0,...,NaN,1.0,46.86,1.0,1.0,2.75,0.0,0,4,2026-09-18 18:22:34.178000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48321,2,2025-01-31 19:36:00,2025-01-31 20:05:00,NaN,179,132,NaN,13.99,55.61,0.0,...,NaN,1.0,68.53,NaN,NaN,NaN,NaN,0,48321,2026-09-18 18:22:34.178000+00:00
48322,2,2025-01-31 20:33:00,2025-01-31 20:41:00,NaN,166,75,NaN,1.51,13.58,0.0,...,NaN,1.0,17.34,NaN,NaN,NaN,NaN,0,48322,2026-09-18 18:22:34.178000+00:00
48323,2,2025-01-31 21:09:00,2025-01-31 21:30:00,NaN,41,42,NaN,2.90,30.89,0.0,...,NaN,1.0,32.39,NaN,NaN,NaN,NaN,0,48323,2026-09-18 18:22:34.178000+00:00
48324,2,2025-01-31 22:22:00,2025-01-31 22:25:00,NaN,75,43,NaN,0.34,14.78,0.0,...,NaN,1.0,18.72,NaN,NaN,NaN,NaN,0,48324,2026-09-18 18:22:34.178000+00:00
48325,2,2025-01-31 22:15:00,2025-01-31 22:22:00,NaN,42,194,NaN,1.37,66.67,0.0,...,NaN,1.0,85.11,NaN,NaN,NaN,NaN,0,48325,2026-09-18 18:22:34.178000+00:00